import { useEffect, useState } from "react";

import { acknowledgeNotification, listNotifications } from "../src/lib/api";
import { NotificationItem } from "../src/lib/types";
import { EmptyState } from "../src/components/EmptyState";
import { ErrorState } from "../src/components/ErrorState";
import { Layout } from "../src/components/Layout";
import { LoadingState } from "../src/components/LoadingState";
import { PageHeader } from "../src/components/PageHeader";
import { Surface } from "../src/components/Surface";

export default function NotificationsPage() {
  const [items, setItems] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function load() {
    setLoading(true);
    setError(null);
    try {
      const payload = await listNotifications(false, 200);
      setItems(payload.items ?? []);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load notifications");
    } finally {
      setLoading(false);
    }
  }

  async function ack(id: string) {
    try {
      await acknowledgeNotification(id);
      await load();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to acknowledge notification");
    }
  }

  useEffect(() => {
    void load();
  }, []);

  return (
    <Layout title="Notifications">
      <div className="page-shell">
        <PageHeader
          title="Operator Inbox"
          subtitle="Research findings, alerts, and acknowledgment-required items that need human awareness before or during autonomous work."
          kicker="Notification Stream"
          actions={<button className="button" onClick={() => void load()}>Refresh Inbox</button>}
          metrics={[{ label: "Unread", value: items.length }]}
        />

        {loading && <LoadingState message="Loading notifications..." />}
        {error && <ErrorState message={error} />}

        <Surface title="Unread Notifications" description="Each item is generated by the orchestrator or supporting agents and can be acknowledged once reviewed.">
          {!loading && !error && items.length === 0 ? (
            <EmptyState message="No unread notifications." />
          ) : items.length > 0 ? (
            <div className="notification-stream">
              {items.map((item) => (
                <div className="notification-item" key={item.id}>
                  <div className="section-header" style={{ marginBottom: 8 }}>
                    <div>
                      <p className="item-title">{item.title}</p>
                      <p className="item-meta">{item.category} · {new Date(item.created_at).toLocaleString()}</p>
                    </div>
                    <button className="secondary-button" onClick={() => void ack(item.id)}>Acknowledge</button>
                  </div>
                  <p className="item-meta">{item.body}</p>
                </div>
              ))}
            </div>
          ) : null}
        </Surface>
      </div>
    </Layout>
  );
}
