from __future__ import annotations

WORKSPACE_POLICY_PROFILES: dict[str, dict[str, object]] = {
    "strict": {
        "allow_write": True,
        "allow_patch": True,
        "allow_read": True,
        "allow_search": True,
        "allow_delete": False,
        "allow_move": False,
        "allow_commands": ("pytest", "python -m pytest"),
        "allowed_actions": (
            "read_file",
            "search_code",
            "write_file",
            "patch_file",
            "run_command",
            "run_test",
            "complete_work",
            "next_action",
            "finish",
        ),
        "timeout_seconds": 90,
        "max_output_chars": 3000,
    },
    "balanced": {
        "allow_write": True,
        "allow_patch": True,
        "allow_read": True,
        "allow_search": True,
        "allow_delete": False,
        "allow_move": True,
        "allow_commands": ("pytest", "python -m pytest", "npm test", "npm run test"),
        "allowed_actions": (
            "read_file",
            "search_code",
            "write_file",
            "patch_file",
            "move_file",
            "run_command",
            "run_test",
            "run_build",
            "run_lint",
            "run_format",
            "complete_work",
            "next_action",
            "finish",
        ),
        "timeout_seconds": 120,
        "max_output_chars": 6000,
    },
    "full-dev": {
        "allow_write": True,
        "allow_patch": True,
        "allow_read": True,
        "allow_search": True,
        "allow_delete": True,
        "allow_move": True,
        "allow_commands": (
            "pytest",
            "python -m pytest",
            "npm test",
            "npm run test",
            "npm run lint",
            "npm run build",
            "uv run pytest",
            "go test",
            "cargo test",
        ),
        "allowed_actions": (
            "read_file",
            "search_code",
            "write_file",
            "patch_file",
            "move_file",
            "delete_file",
            "run_command",
            "run_test",
            "run_build",
            "run_lint",
            "run_format",
            "run_targeted_test",
            "install_deps",
            "complete_work",
            "next_action",
            "finish",
        ),
        "timeout_seconds": 180,
        "max_output_chars": 10000,
    },
}
